models/__init__.py
from .base import db

models/base.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

__all__ = [
    "db",
]

models/post.py
from werkzeug.exceptions import NotFound
from sqlalchemy import Column, Integer, String, Text, Boolean, ForeignKey
from sqlalchemy.orm import relationship
from models import db
from models.user import User
from models.theme import Theme


class Post(db.Model):
    __tablename__ = "posts"

    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    title = Column(String(50), nullable=False)
    html = Column(Text, nullable=False)
    main_photo = Column(Text, nullable=False)
    theme_id = Column(Integer, ForeignKey('themes.id'), nullable=False)
    is_published = Column(Boolean, nullable=False, default=False, server_default="0")

    user = relationship(User, back_populates="posts")
    theme = relationship(Theme, back_populates="posts")

    def __str__(self):
        return str(self.title)

    def __repr__(self):
        return str(self)

    @classmethod
    def get_post_by_id(cls, post_id):
        post = cls.query.filter_by(id=post_id).one_or_none()
        if post is None:
            raise NotFound(f"Post #{post_id} not found")
        return post

models/theme.py
from werkzeug.exceptions import NotFound
from sqlalchemy import Column, Integer, String
from sqlalchemy.orm import relationship
from models import db


class Theme(db.Model):
    __tablename__ = "themes"

    id = Column(Integer, primary_key=True)
    theme_en = Column(String(30), nullable=False)
    theme_ru = Column(String(30), nullable=False)

    posts = relationship("Post", back_populates="theme")

    def __str__(self):
        return str(self.theme_en)

    def __repr__(self):
        return str(self)

    @classmethod
    def get_theme_by_id(cls, theme_id):
        theme = cls.query.filter_by(id=theme_id).one_or_none()
        if theme is None:
            raise NotFound(f"Theme #{theme_id} not found")
        return theme

models/user.py
from werkzeug.exceptions import NotFound
from sqlalchemy import Column, Integer, String
from sqlalchemy.orm import relationship
from models import db


class User(db.Model):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True)
    username = Column(String(30), nullable=False)
    name = Column(String(30), nullable=False)
    surname = Column(String(30), nullable=False)

    userpic = Column(String, nullable=False)

    posts = relationship("Post", back_populates="user")

    def __str__(self):
        return str(self.username)

    def __repr__(self):
        return str(self)

    @classmethod
    def get_user_by_id(cls, user_id):
        user = cls.query.filter_by(id=user_id).one_or_none()
        if user is None:
            raise NotFound(f"User #{user_id} not found")
        return user

app.py
from flask import Flask, render_template
import config
from models.base import db
from models.post import Post
from views.posts import post_app
from views.users import user_app

app = Flask(__name__)
app.register_blueprint(post_app, url_prefix="/posts")
app.register_blueprint(user_app, url_prefix="/users")

app.config.update(
    SQLALCHEMY_DATABASE_URI=config.SQLALCHEMY_DATABASE_URI,
    SQLALCHEMY_TRACK_MODIFICATIONS=False,
)
db.init_app(app)


@app.route("/", methods=["GET", "POST"], endpoint="index")
def index():
    posts = Post.query.order_by(Post.id.desc()).limit(3).all()
    return render_template("index.html", posts=posts)


@app.cli.command('init-db', with_appcontext=True)
def initialize_db():
    """
    Create initial sqlite db
    """
    print("Do init db")
    db.create_all()
    print("Init db done")


if __name__ == "__main__":
    app.run(
        host="0.0.0.0",
        port=5000,
        debug=True
    )

main.py
"""Наполнение тестовыми данными бд"""

from add_data import add_some_data
from models.base import db
from sqlalchemy.orm import Session
from sqlalchemy import create_engine
import config


if __name__ == '__main__':
    engine = create_engine(config.SQLALCHEMY_DATABASE_URI)
    db.Model.metadata.create_all(engine)
    session = Session(bind=engine)
    add_some_data(session)
    session.close()

views/posts.py
"""Blueprint с /posts/"""

from flask import Blueprint, render_template
from models.post import Post

post_app = Blueprint("post_app", __name__)


@post_app.route("/", endpoint="posts_list")
def post_list():
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template("posts/post_list.html", posts=posts, theme_en='all')


@post_app.route("/<string:theme_en>/", endpoint="posts_theme")
def post_theme(theme_en):
    posts = Post.query.filter(Post.theme.has(theme_en=theme_en)).order_by(Post.id.desc()).all()
    return render_template("posts/post_list.html", posts=posts, theme_en=theme_en)


@post_app.route("/<int:post_id>/", endpoint="post_detail")
def post_detail(post_id):
    post = Post.get_post_by_id(post_id)
    return render_template(post.html, post=post)

views/users.py
"""Blueprint с /users/"""

from flask import Blueprint, render_template
from models.user import User
from models.post import Post


user_app = Blueprint("user_app", __name__)


@user_app.route("/", endpoint="users_list")
def user_list():
    users = User.query.order_by(User.id.desc()).all()
    return render_template("users/user_list.html", users=users)


@user_app.route("/<int:user_id>/", endpoint="user_detail")
def user_detail(user_id):
    user = User.get_user_by_id(user_id)
    posts = Post.query.filter(Post.user.has(id=user_id)).order_by(Post.id.desc()).all()

    return render_template('users/user_detail.html', user=user, posts=posts)

templates/author_info.html
<div class="author-info">
    <a class="post-link" href="{{ url_for('user_app.user_detail', user_id=post.user.id)}}">
        <img class="post-author-img" src={{ post.user.userpic }}>
    </a>

    <a class="post-link" href="{{ url_for('user_app.user_detail', user_id=post.user.id) }}">
    <h2 class=post-author>{{ post.user.name }} {{ post.user.surname }}</h2>
    </a>
</div>

templates/designed_posts/alei-journal-stas.html
{% extends './posts/post_base.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    {% block post_info %}
        {{ super() }}
    {% endblock %}

    <div class="info-blocks">
        <div class="info-block">
            <p class="post-text">Cтас Калашников - российский фотограф и режиссер, проживающий в Париже.</p>
            <p class="post-text">
                alei journal - это коллекция портфолио и интервью художников,
                свободных произведений от поэзии до художественной литературы и многочисленных серий фотографий,
                представленных международными фотографами. Каждый вкладчик волен вкладывать свое пространство по своему усмотрению,
                и журнал намерен работать как выставочное издание.
            </p>
            <p class="post-text">
                Через призму естественной идентичности света, цветов и лексики alei journal исследует такие темы,
                как близость, индивидуальность и телесные отношения. Отсутствие фильтров и ретуши,
                а также полная свобода творчества предлагают авторам журнала подлинную зону самовыражения и чувствительности.
            </p>
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/alei-journal-stas/-7_alejournal_StasKalashnikov2_800.jpg" alt="photo Stas Kalashnikov for alejournal">
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/alei-journal-stas/-7_alejournal_StasKalashnikov5_800.jpg" alt="photo Stas Kalashnikov for alejournal">
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/alei-journal-stas/-7_alejournal_StasKalashnikov6_800.jpg" alt="photo Stas Kalashnikov for alejournal">
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/alei-journal-stas/-7_alejournal_StasKalashnikov7_800.jpg" alt="photo Stas Kalashnikov for alejournal">
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/alei-journal-stas/-7_alejournal_StasKalashnikov9_800.jpg" alt="photo Stas Kalashnikov for alejournal">
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/alei-journal-stas/-7_alejournal_StasKalashnikov11_800.jpg" alt="photo Stas Kalashnikov for alejournal">
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/alei-journal-stas/stas-kalashnikov-main.jpg" alt="photo Stas Kalashnikov for alejournal">
        </div>
    </div>
{% endblock %}

templates/designed_posts/david-hockney.html
{% extends './posts/post_base.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    {% block post_info %}
        {{ super() }}
    {% endblock %}

    <div class="info-blocks">
        <div class="info-block">
            <p class="post-text">
                В этом году исполнилось 82 года Дэвиду Хокни — одному из самых влиятельных и дерзких британских художников двадцатого века и ключевой фигуре движения поп-арта,
                который одним из первых открыто заговорил на языке живописи и фотографии об однополой любви.
                От фотоколлажей и оперных афиш до вдохновленных кубизмом абстракций и деревенских пейзажей:
                за более чем шестидесятилетнюю карьеру Хокни успел попробовать себя в самых разных жанрах и направлениях.
                Решительно шагнувший в век технологий легендарный художник и сегодня продолжает искать и находить новые способы выражения,
                оставаясь при этом все тем же бунтарём верным своей любви к ярким краскам и смелым композициям.
            </p>
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/david-hockney/Hockney.jpg" alt="Photo of piece of art David Hockney by Mark Mahaney">
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/david-hockney/david-hockney-main.jpg" alt="Photo of David Hockney by Mark Mahaney">
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/david-hockney/h1200_mark_mahaney_18742c7c.jpg" alt="Photo of David Hockney by Mark Mahaney">
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/david-hockney/h1200_mark_mahaney_12c3b0b4.jpg" alt="Photo of David Hockney by Mark Mahaney">
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/david-hockney/h1200_mark_mahaney_e0a504fa.jpg" alt="Photo of David Hockney by Mark Mahaney">
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/david-hockney/h1200_mark_mahaney_cb5d8dc5.jpg" alt="Photo of David Hockney by Mark Mahaney">
        </div>
    </div>
{% endblock %}

templates/designed_posts/helmut-lang-home-pasternak.html
{% extends './posts/post_base.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    {% block post_info %}
        {{ super() }}
    {% endblock %}

    <div class="info-blocks">
        <div class="info-block">
            <p class="post-text">
                Бренд Helmut Lang запустил проект Helmut At Home. В нем друзья бренда и вдохновляющие люди показывают, как проводят карантин.
            </p>
            <p class="post-text">
                В проекте приняли участие Таня и Женя Постернак, сестры-фотографы из Киева, которые живут и работают в Нью-Йорке.
                Для Helmut Lang они сняли серию фотографий с полупрозрачным голубым свитером.
            </p>
            <p class="post-text">
                Сестры известны по работам для бренда Mansur Gavriel. Они также снимают для американского Vogue и The New York Times.
                Для Allure они сняли обложку с теннисисткой Сереной Уильямс.
            </p>

            <p class="post-text">
                Ранее в проекте Helmut At Home приняли участие модели Лили Самнер и Анин ван Вельцен и актер Нико Хирага.
                Лили поделилась книгами, которые успела прочитать в изоляции,
                а Нико показал, как занимается скейтбордингом на террасе и проводит время с собакой.
            </p>

        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/helmut-lang-home-pasternak/helmut-at-home-posternak-01.jpg" alt="Photo for Helmut at home">
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/helmut-lang-home-pasternak/helmut-lang-main.jpg" alt="Photo for Helmut at home">
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/helmut-lang-home-pasternak/photo_2021-03-01_20-44-56.jpg" alt="Photo for Helmut at home">
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/helmut-lang-home-pasternak/photo_2021-03-01_20-45-02.jpg" alt="Photo for Helmut at home">
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/helmut-lang-home-pasternak/photo_2021-03-01_20-45-05.jpg" alt="Photo for Helmut at home">
        </div>

    </div>

{% endblock %}

templates/designed_posts/jil-sander-ss21.html
{% extends './posts/post_base.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    {% block post_info %}
        {{ super() }}
    {% endblock %}

    <div class="info-blocks">
        <div class="info-block">
            <p class="post-text">Героинями съемки стали Лили Макменами и Саския де Брау.</p>
            <p class="post-text">
                Jil Sander посвятил новую кампанию важности тактильного контакта и близости между людьми.
                Кампания весна-лето 2021 доступна на официальном сайте бренда.
                «Мы хотели интерпретировать темы прикосновений, близости, дружбы», — поделились креативные директоры Jil Sander Люси и Люк Мейер.
            </p>
            <p class="post-text">
                Jil Sander посвятил новую кампанию важности тактильного контакта и близости между людьми.
                Кампания весна-лето 2021 доступна на официальном сайте бренда.
                «Мы хотели интерпретировать темы прикосновений, близости, дружбы», — поделились креативные директоры Jil Sander Люси и Люк Мейер.
            </p>

            <p class="post-text">
                Ранее вышел лукбук межсезонной коллекции Jil Sander. Его снимали в квартире, для того чтобы добиться домашней атмосферы.
            </p>
        </div>
        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/jil-sander-ss21/JilsanderSS21_NIGEL_L_01.jpg" alt="Photo Jil Sander Campaign">
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/jil-sander-ss21/1611159637734551.jpg" alt="Photo Jil Sander Campaign">
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/jil-sander-ss21/1611159638080666.jpg" alt="Photo Jil Sander Campaign">
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/jil-sander-ss21/JilsanderSS21_NIGEL_L_04.jpg" alt="Photo Jil Sander Campaign">
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/jil-sander-ss21/JilsanderSS21_NIGEL_L_06.jpg" alt="Photo Jil Sander Campaign">
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/jil-sander-ss21/JilsanderSS21_SHANIQWA_L_01.jpg" alt="Photo Jil Sander Campaign">
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/jil-sander-ss21/jil-sander-main.jpg" alt="Photo Jil Sander Campaign">
        </div>

    </div>
{% endblock %}

templates/designed_posts/polar-night-mark.html
{% extends './posts/post_base.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    {% block post_info %}
        {{ super() }}
    {% endblock %}

    <div class="info-blocks">
        <div class="info-block">
            <p class="post-text">«Polar Night» рассказывает о повседневной жизни отдаленного города, расположенного более чем в 400 км к северу от Полярного круга.</p>
            <p class="post-text">
                Utqiagvik (ранее известный как Barrow) - крупнейший город и правительственный центр округа North Slope Borough на Аляске.
                Это одно из самых северных общественных сообществ в мире. Главной целью Mahaney было раскрыть распорядок жизни людей, живущих в этом месте,
                где ночь длится два невыносимо долгих месяца, а продукты доставляются по воздуху в определенные даты.
                Раскрывая повседневную жизнь жителей с помощью фотографий зданий, обмерзших автомобилей и сторожевых собак со сверкающими клыками,
                он обнаружил еще один важный аспект, который добавляет дополнительный слой в его историю: реакцию жителей на изменение климата.
            </p>
        </div>
        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/polar-night-mark/h1200_mark_mahaney_8a74709d.jpg" alt="Photo Mark Mahaney Polar Night">
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/polar-night-mark/polar-night-main.jpg" alt="Photo Mark Mahaney Polar Night">
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/polar-night-mark/h1200_mark_mahaney_f45b8b00.jpg" alt="Photo Mark Mahaney Polar Night">
        </div>

        <div class="info-block">
            <p class="post-text">
                «Никакие дороги не ведут.
                Ни растений, ни деревьев, ни свежих продуктов, кроме того, на что охотятся: гренландского кита, тюленя, карибу, моржа, белого медведя »,
                - сообщает Mark Mahaney. Так темно. Так холодно, что ничего не чувствуешь.
                В «дневное время» он видел людей, спешащих на работу или в продуктовый магазин; ночью улицы были безлюдны.
                Он совершал ночные походы и фотографировал, как здания и автомобили покрываются слоями снега.
                Так же, Mahaney сумел передать в контрастных теплых тонах определенное ощущение комфорта в этом городе.
                Или, по крайней мере, сокрытую перспективу светлого будущего впереди - в конце полярной ночи.

            </p>
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/polar-night-mark/h1200_mark_mahaney_69c279a2.jpg" alt="Photo Mark Mahaney Polar Night">
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/polar-night-mark/h1200_mark_mahaney_0dae647e.jpg" alt="Photo Mark Mahaney Polar Night">
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/polar-night-mark/h1200_mark_mahaney_1a7bb06d.jpg" alt="Photo Mark Mahaney Polar Night">
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/polar-night-mark/h1200_mark_mahaney_8f5f772c.jpg" alt="Photo Mark Mahaney Polar Night">
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/polar-night-mark/h1200_mark_mahaney_072e17e3.jpg" alt="Photo Mark Mahaney Polar Night">
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/polar-night-mark/h1200_mark_mahaney_76f7ef10.jpg" alt="Photo Mark Mahaney Polar Night">
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/polar-night-mark/h1200_mark_mahaney_9ca4d49e.jpg" alt="Photo Mark Mahaney Polar Night">
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/polar-night-mark/h1200_mark_mahaney_a4fd38b4.jpg" alt="Photo Mark Mahaney Polar Night">
        </div>

        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/polar-night-mark/h1200_mark_mahaney_c9b0e991.jpg" alt="Photo Mark Mahaney Polar Night">
        </div>

    </div>
{% endblock %}

templates/designed_posts/ysl-fw21.html
{% extends './posts/post_base.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    {% block post_info %}
        {{ super() }}
    {% endblock %}

    <div class="info-blocks">
        <div class="info-block">
            <p class="post-text">В Париже прошел показ Saint Laurent осень–зима 2020/2021.
                Шоу в очередной раз прошло на площади Трокадеро, на фоне Эйфелевой башни — и под тяжелые биты французского электронного музыканта SebastiAn,
                который пишет треки для шоу и рекламных кампаний бренда с 2017-го.
                А главным героем шоу стал латекс — материал со сложной историей, которому Энтони Ваккарелло буквально подарил новую, благородную жизнь.
            </p>
        </div>
        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/ysl-fw21/093e814d2f9647100deb7e47672a8fec_3482.jpg" alt="Photo Saint Laurent Campaign">
        </div>
        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/ysl-fw21/saint-laurent-main.jpg" alt="Photo Saint Laurent Campaign">
        </div>
        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/ysl-fw21/3a87b6f2225fd746fa42af2c3297764e_3482.jpg" alt="Photo Saint Laurent Campaign">
        </div>
        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/ysl-fw21/8d5d6b920deab1bf0ebfe01bc4e076de_3482.jpg" alt="Photo Saint Laurent Campaign">
        </div>
        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/ysl-fw21/8702d6a6ff7c80ff9535637feca4c200_3482.jpg" alt="Photo Saint Laurent Campaign">
        </div>
        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/ysl-fw21/737c10572178e5cb40ad1084d4017e00_3482.jpg" alt="Photo Saint Laurent Campaign">
        </div>
        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/ysl-fw21/a12cd451ce76abd1886d0b914cd0fd94_3482.jpg" alt="Photo Saint Laurent Campaign">
        </div>
        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/ysl-fw21/c3c61bb696658760e65f6ed6b49f3b3a_3482.jpg" alt="Photo Saint Laurent Campaign">
        </div>
        <div class="info-block">
            <img class=post-image src="https://vision-assistant.netlify.app//img/ysl-fw21/ebc029f948a4ea2596e65378eb2e1716_3482.jpg" alt="Photo Saint Laurent Campaign">
        </div>
    </div>
{% endblock %}

templates/index.html
{% extends './posts/post_list.html' %}

{% block title %}
    Visual Assistant
{% endblock %}

templates/index_base.html
<!DOCTYPE HTML>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>
        {% block title %}
            Base
        {% endblock %}
    </title>

    <link rel="icon" href="{{ url_for('static', filename='favicon_io/favicon.ico') }}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Orbitron&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Jura:wght@300;500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Jura:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">

</head>
<body>


<header class="header">
    <div class="content-header">
        <div class="limit-header">
            <a href="{{ url_for("index") }}"
               class="main_logo_title"
               title="Visual Assistant — блог о моде, искусстве и фотографии">Visual<br>Assistant
            </a>
            <ul class="menu">

                <li class="menu-point">
                    <a class="menu-link link1  {% if theme_en=='photo' %} theme-photo {% endif %}"
                       href="{{ url_for("post_app.posts_theme", theme_en='photo') }}">фото</a>
                </li>

                <li class="menu-point"><div class="menu-splitter">|</div></li>

                <li class="menu-point">
                    <a class="menu-link link2 {% if theme_en=='fashion' %} theme-fashion {% endif %}"
                       href="{{ url_for("post_app.posts_theme", theme_en='fashion') }}">мода</a>
                </li>

                <li class="menu-point"><div class="menu-splitter">|</div></li>

                <li class="menu-point">
                    <a class="menu-link link3 {% if theme_en=='art' %} theme-art {% endif %}"
                       href="{{ url_for("post_app.posts_theme", theme_en='art') }}">искусство</a></li>

                <li class="menu-point"><div class="menu-splitter">|</div></li>

                <li class="menu-point">
                    <a class="menu-link link4 {% if theme_en=='all' %} theme-all {% endif %}"
                       href="{{ url_for("post_app.posts_list") }}">всё</a></li>
            </ul>
        </div>
    </div>
</header>


<section class=content>
    {% block content %}
        <h1>Base content</h1>
    {% endblock %}
</section>

<div class="marquee">
    <span>Оставайтесь на связи</span>
    <span>Оставайтесь на связи</span>
    <span>Оставайтесь на связи</span>
    <span>Оставайтесь на связи</span>
    <span>Оставайтесь на связи</span>
    <span>Оставайтесь на связи</span>
</div>

<footer class="footer">
    <div class="footer-container">
        <div class="footer-message">
            <h2 class="footer-header">Контакты</h2>
            <span>admin@visualass.com</span>
            <span>
                <a class="footer-link link-tg" href="https://t.me/maksimovv" target="_blank">TG</a>
                <a class="footer-link link-ig" href="https://www.instagram.com" target="_blank">IG</a>
            </span>
            <span>Visual Assistant 2021</span>
        </div>
    </div>
</footer>

</body>
</html>

templates/posts/post_base.html
{% extends 'index_base.html' %}

<section class=content-post>
    {% block content %}
        {% block post_info %}
            <div class="post-info">
                <h2 class="post-title post-header">{{ post.title }}</h2>
                {% include 'author_info.html' %}
            </div>
        {% endblock %}
    {% endblock %}
</section>

templates/posts/post_list.html
{% extends 'index_base.html' %}

{% block title %}
    Visual Assistant - {{ theme_en.capitalize() }}
{% endblock %}

{% block content %}
    {% for post in posts %}
            <div class=post>

                <div class="post-top-block">
                    {% include 'author_info.html' %}
                    <h3 class="post-theme theme-{{ post.theme.theme_en }}">{{ post.theme.theme_ru }}</h3>
                </div>

                <a class="post-link" href="{{ url_for('post_app.post_detail', post_id=post.id)}}">
                    <img class=post-image
                         src="{{ post.main_photo }}"
                         alt= "Main photo for post - {{ post.title }}" >
                </a>

                <a class="post-link" href="{{ url_for('post_app.post_detail', post_id=post.id)}}">
                    <h2 class=post-title-link>{{ post.title }}</h2>
                </a>

            </div>
    {% endfor %}

{% endblock %}

templates/users/user_detail.html
{% extends './posts/post_list.html' %}

{% block title %}
    Visual Assistant - {{ user.username }}
{% endblock %}

templates/users/user_list.html
{% extends 'index_base.html' %}

{% block title %}
    Visual Assistant - Users
{% endblock %}

{% block content %}
    {% for user in users %}
            <div class=post>

                <div class="author-info">
                    <a class="post-link" href="{{ url_for('user_app.user_detail', user_id=user.id)}}">
                        <img class="post-author-img" src={{ user.userpic }}>
                    </a>

                    <a class="post-link" href="{{ url_for('user_app.user_detail', user_id=user.id) }}">
                    <h2 class=post-author>{{user.name }} {{ user.surname }}</h2>
                    </a>
                </div>

            </div>
    {% endfor %}

{% endblock %}